IF_PATTERN = r'if\s*\(.+?\)'
FOR_PATTERN = r'for\s*\(.+?\)'
WHILE_PATTERN = r'while\s*\(.+?\)'
FOREACH_PATTERN = r'foreach\s*\(.+?\)'
METHOD_PATTERN = r'\b[A-Z]\w*(?=\s*\()'
USINGS_PATTERN = r'^using\s+[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*;$'
CODELINES_PATTERN = r'^[^\n].*\S'
COMMENTS_PATTERN = r'^[^\n]*(?:(?:\/\/[^\n]*)|(?:\/\*[\s\S]*?\*\/)|\S.*(?:\/\/[^\n]*|\/\*[\s\S]*?\*\/))'