IF_PATTERN = r'if\s*\(.+?\)'
FOR_PATTERN = r'for\s*\(.+?\)'
WHILE_PATTERN = r'while\s*\(.+?\)'
FOREACH_PATTERN = r'foreach\s*\(.+?\)'
USINGS_PATTERN = r'^using\s+[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*;$'
CODELINES_PATTERN = r'^[^\n].*\S'
COMMENTS_PATTERN = r'^[^\n]*(?:(?:\/\/[^\n]*)|(?:\/\*[\s\S]*?\*\/)|\S.*(?:\/\/[^\n]*|\/\*[\s\S]*?\*\/))'
METHOD_PATTERN = r'\b(?:public|private|protected|internal|static|virtual|override|abstract|sealed|partial|async)?\s+\w+\s+\w+\s*\([^)]*\)\s*{[^}]*}'
CLASS_PATTERN = r'class\s+\w+(\s*<[a-zA-Z0-9, ]+>)?'
INTERFACE_PATTERN = r'public\s*interface\s+\w+\s*{[^}]*}'
CLASS_COUPLING = r'\b[A-Z][A-Za-z0-9_]*(?:<[A-Za-z][A-Za-z0-9_]*>)?(?!(?:\s*\{|;|\s*\=)|\s*\.|\s*\-|\s*\?|s*\+|\s*\(|\s*\,|\s*\:|\s*\}|\s*\)|\s*\\)\b'